<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXoOgxhv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXoOgxhv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXoOgxhv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXoOgxhv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXoOgxhv\App_KernelDevDebugContainer([
    'container.build_hash' => 'XoOgxhv',
    'container.build_id' => 'c0b2b13f',
    'container.build_time' => 1619377218,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXoOgxhv');
