<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAtIXadd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAtIXadd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAtIXadd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAtIXadd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAtIXadd\App_KernelDevDebugContainer([
    'container.build_hash' => 'AtIXadd',
    'container.build_id' => '169da997',
    'container.build_time' => 1616182409,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAtIXadd');
