<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGbmBj0y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGbmBj0y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGbmBj0y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGbmBj0y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGbmBj0y\App_KernelDevDebugContainer([
    'container.build_hash' => 'GbmBj0y',
    'container.build_id' => 'b583dd28',
    'container.build_time' => 1619301129,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGbmBj0y');
